server:
  port: 8095
  max-http-header-size: 102400

spring:
  datasource:
    url: jdbc:mysql://10.91.0.104:3307/test_user?useSSL=false&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 5rfv7ujmd
    driver-class-name: org.mariadb.jdbc.Driver
  redis:
    password: ebbf6efa83d1d1730ee90b9da7d1175f
    database: 1
    port: 6379
    host: 10.91.0.101
    lettuce:
      pool:
        max-idle: 8   # 连接池中的最大空闲连接
        min-idle: 0   # 连接池中的最小空闲连接
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 1000ms   # 连接超时时间（毫秒）

swagger:
  enable: true

logging:
  level:
    com:
      cetus:
        securitydemo:
          mapper: debug
